### ISSUE TITLE
Permetre de mettre un vote positif

### ISSUE THREAD

**Issue by gamazeps** [richoux/jenevotepluspourvous.fr#2]
Ca servirait 2 buts :
- Si on souhaite vraiment être pertinents, ça permettrai de voire qui voterai pour un député parce qu'il a voté pour la loi, mettre juste le négatif ne me parait pas très honnête (j'epère que cet usage sera anecdotique).
- Cela permet aussi de montrer à un député que son vote contre a été aprécié et du coup lui permettre de continuer dans cette voie (je suis très content de mon député qui n'est pas membre du parti auquel je m'identifie, mais qui vote très souvent en accord avec mes convictions et pour lequel je compte donc voter).

Techniquement ça ne sera pas spécialement plus compliqué.

Bonne initiative btw ;)

**Comment by richoux** [comment]
Merci pour vos commentaires. Je vois cependant un problème : ça peut rendre le site comme un lieu de bataille entre partisans et opposants à cette loi, avec des gens cliquant et re-cliquant pour faire monter le score qui les arrange. En effet je ne souhaite pas mettre de mécanisme pour empêcher une personne de cliquer plusieurs fois, pour plusieurs raisons : 
1. Forcer les gens à mettre une adresse email afin de leur envoyer un message leur permettant de voter me semble à la fois un peu compliqué d'un point de vue technique (bien plus technique en tout cas que ce qui est prévu à la base pour ce site) et lourd : ça va rebuter pleins de gens. Surtout que l'on peut toujours tricher si on a plusieurs comptes mail.
2. "une IP = un vote" n'est pas souhaitable non plus. Quid des personnes vivants sous le même toit ? Et pour les gens qui ont une adresse IP dynamique ? De toute façon, il me semble assez ironique qu'un site dénonçant la PJLRenseignement flique les gens en retenant leur adresse IP...

Donc pour que ça ne devienne pas une foire d'empoigne, je ne pense pas qu'il faille mettre deux types de vote possible. Et puis après tout, le nom du site est "jenevotepluspourvous". Le nom de domaine est déjà loué.
